### ISSUE TITLE
Generated patch incorrect for Array replacement

### ISSUE THREAD

**Issue by tamalsaha** [appscode/jsonpatch#1]
Here is a case that produces buggy patch:

```
src = {
  "spec": {
    "loadBalancerSourceRanges": [
      "192.101.0.0/16",
      "192.0.0.0/24"
    ]
  }
}

dst = {
  "spec": {
    "loadBalancerSourceRanges": [
      "192.101.0.0/24"
    ]
  }
}
```

The generated patch is:
```
[
  {
    "op": "remove",
    "path": "/spec/loadBalancerSourceRanges/0"
  },  
  {
    "op": "remove",
    "path": "/spec/loadBalancerSourceRanges/1"
  },
  {
    "op": "add",
    "path": "/spec/loadBalancerSourceRanges/0",
    "value": "192.101.0.0/24"
  }
]
```

This results in an error. The problem seems to be that index 1 should be removed before index 0. If I reverse the order the generated patch works.

I tested patch generation using https://github.com/stefankoegl/python-json-patch library . This produces a valid patch:
```
[{"path": "/spec/loadBalancerSourceRanges/1", "op": "remove"}, {"path": "/spec/loadBalancerSourceRanges/0", "value": "192.101.0.0/24", "op": "replace"}]
```

https://gist.github.com/tamalsaha/e8b313aec8f8d8191bc01ba504247e30

I also tested against a node.js library here: https://json8.github.io/patch/demos/apply/ . I get the same issue.

**Comment by nylon22** [comment]
I was having the same issue, so I used your fork in my project, but it didn't fix it for me.

The issue I had, which seems to be the same as this, was if `src` was `["A", "B", "C"]` and `to` was `["D"]`, the patch that was generated causes the library I'm using to apply the patch to try to replace "A" with "D", and then remove index **1** and _then_ index **2**. But after index **1** is removed, there is no index **2** anymore, causing an "Index out of bounds exception" trying to apply the patch.

My fix was to sort removals alphabetically by path and also numerically by path index (in case index >=10) in descending order, so that in the scenario above, index **2** gets removed _before_ index **1**. 

[Here](https://github.com/nylon22/jsonpatch/commits/master) are my changes. Would you be interested in a PR?

**Comment by tamalsaha** [comment]
Patch is welcome!
